### ISSUE TITLE
ACORN crashes when you click on project queued for sync...  "Show details" 

### ISSUE THREAD

**Issue by adamth0mps0n** [h-be/acorn#68]
Stack trace shows the following:
Cannot read property 'replace' of undefined

TypeError: Cannot read property 'replace' of undefined
    at ns (file:///tmp/.mount_Acorn-hyp3Ji/resources/app.asar/web/main.js:351:265522)
    at file:///tmp/.mount_Acorn-hyp3Ji/resources/app.asar/web/main.js:351:279003
    at Array.map (<anonymous>)
    at Ds (file:///tmp/.mount_Acorn-hyp3Ji/resources/app.asar/web/main.js:351:278865)
    at Za (file:///tmp/.mount_Acorn-hyp3Ji/resources/app.asar/web/main.js:309:57951)
    at Fi (file:///tmp/.mount_Acorn-hyp3Ji/resources/app.asar/web/main.js:309:66806)
    at ws (file:///tmp/.mount_Acorn-hyp3Ji/resources/app.asar/web/main.js:309:105552)
    at xl (file:///tmp/.mount_Acorn-hyp3Ji/resources/app.asar/web/main.js:309:96859)
    at bl (file:///tmp/.mount_Acorn-hyp3Ji/resources/app.asar/web/main.js:309:96784)
    at fl (file:///tmp/.mount_Acorn-hyp3Ji/resources/app.asar/web/main.js:309:93807)

**Comment by Connoropolous** [comment]
Thanks @adamth0mps0n 
We encountered that too.

**Comment by adamth0mps0n** [comment]
V5.9 fixes this issue.. Closing.

**Comment by Connoropolous** [comment]
Thanks @adamth0mps0n we did fix that, and we also made some changes and (hopefully) improvements to the joining project flow. Can you let us know if any old or new issues arise with that, or about your user experience?
