### ISSUE TITLE
Can't run locally, scripts/install-hc-tools.sh: line 12: --rev: command not found

### ISSUE THREAD

**Issue by felri** [h-be/acorn#8]
Rust is installed, when I try to run `npm run dna-install-deps` I'm able to install the rust libs but after I receive this message: `scripts/install-hc-tools.sh: line 12: --rev: command not found` and the installation is closed with an error

I'm using a m1 mac, I don't know if this has any impact.

cargo 1.52.0 (69767412a 2021-04-21)
node v14.16.1
rustup 1.24.1 (a01bd6b0d 2021-04-27)

Full log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/felipemelo/.nvm/versions/node/v12.22.1/bin/node',
1 verbose cli   '/Users/felipemelo/.nvm/versions/node/v12.22.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dna-install-deps'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose run-script [ 'predna-install-deps', 'dna-install-deps', 'postdna-install-deps' ]
5 info lifecycle acorn@1.0.0~predna-install-deps: acorn@1.0.0
6 info lifecycle acorn@1.0.0~dna-install-deps: acorn@1.0.0
7 verbose lifecycle acorn@1.0.0~dna-install-deps: unsafe-perm in lifecycle true
8 verbose lifecycle acorn@1.0.0~dna-install-deps: PATH: /Users/felipemelo/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/felipemelo/Documents/me/acorn/node_modules/.bin:/Users/felipemelo/.nvm/versions/node/v12.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/felipemelo/.cargo/bin
9 verbose lifecycle acorn@1.0.0~dna-install-deps: CWD: /Users/felipemelo/Documents/me/acorn
10 silly lifecycle acorn@1.0.0~dna-install-deps: Args: [ '-c', '. scripts/install-hc-tools.sh' ]
11 info lifecycle acorn@1.0.0~dna-install-deps: Failed to exec dna-install-deps script
12 verbose stack Error: acorn@1.0.0 dna-install-deps: `. scripts/install-hc-tools.sh`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/Users/felipemelo/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:314:20)
12 verbose stack     at maybeClose (internal/child_process.js:1022:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid acorn@1.0.0
14 verbose cwd /Users/felipemelo/Documents/me/acorn
15 verbose Darwin 20.3.0
16 verbose argv "/Users/felipemelo/.nvm/versions/node/v12.22.1/bin/node" "/Users/felipemelo/.nvm/versions/node/v12.22.1/bin/npm" "run" "dna-install-deps"
17 verbose node v12.22.1
18 verbose npm  v6.14.12
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error acorn@1.0.0 dna-install-deps: `. scripts/install-hc-tools.sh`
23 error spawn ENOENT
24 error Failed at the acorn@1.0.0 dna-install-deps script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by Connoropolous** [comment]
Hey thanks.

Looks like a \ got missed when I uncomment a line. Add a \ to the end of line 11 and it should fully run then

**Comment by Connoropolous** [comment]
I will fix in the repo
