### ISSUE TITLE
Acorn crashes when trying to assign a parent node as child node to its child

### ISSUE THREAD

**Issue by bierlingm** [h-be/acorn#9]
```
Cannot read property 'x' of undefined

TypeError: Cannot read property 'x' of undefined
    at Function.mapToProps (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:358:67824)
    at r (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:351:164151)
    at h (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:351:165752)
    at file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:351:165824
    at e.f [as onStateChange] (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:351:157972)
    at e.t.handleChangeWrapper (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:351:155880)
    at file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:351:156263
    at pl (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:309:94074)
    at Object.notify (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:351:156232)
    at e.t.notifyNestedSubs (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:351:155812)
```

**Comment by Connoropolous** [comment]
hey @bierlingm ! thanks for reporting. Out of curiosity, how were you able to even attempt that, because usually by design it disallows you from creating that connection?

**Comment by Connoropolous** [comment]
Aha, I see. I was able to reproduce by having the child node selected. Without having it selected, you would have to move your mouse very very quickly to make that connection.

**Comment by bierlingm** [comment]
Interesting, thanks!
